=== yaroslava-l/OOP/lab2/Tariff.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

<xs:element name="operator" type="newOperator"/>
<xs:complexType name="newOperator">
    <xs:sequence>
        <xs:element name="tariff" type="tariff" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="name" type="xs:string" use="required"/>
</xs:complexType>

<xs:complexType name="tariff">
    <xs:sequence>
        <xs:element name="tariffname" type="xs:string"/>
        <xs:element name="payroll" type="xs:double"/>
        <xs:element name="callprices">
            <xs:complexType>
               <xs:sequence>
            <xs:element name="insidenetwork" type="xs:double"/>
            <xs:element name="outsidenetwork" type="xs:double"/>
            <xs:element name="tofixedphones" type="xs:double"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element>    
        <xs:element name="smsprice" type="xs:double"/>
        <xs:element name="parameters">
            <xs:complexType>
               <xs:sequence>
                    <xs:element name="favouritenumbers" type="xs:positiveInteger"/>
                    <xs:element name="tariffing" type="tariffing"/>
                    <xs:element name="connectpayment" type="xs:double"/>
                </xs:sequence>
            </xs:complexType>
        </xs:element> 
</xs:sequence>
    <xs:attribute name="id" type="xs:ID" use="required"/>    
</xs:complexType> 

<xs:simpleType name="insidenetwork">
    <xs:restriction base="xs:double">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="10"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="outsidenetwork">
    <xs:restriction base="xs:double">
        <xs:minInclusive value="10"/>
        <xs:maxInclusive value="20"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="tofixedphones">
    <xs:restriction base="xs:double">
        <xs:minInclusive value="5"/>
        <xs:maxInclusive value="40"/>
    </xs:restriction>
</xs:simpleType>
    
<xs:simpleType name="smsprice">
        <xs:restriction base="xs:double">
            <xs:minInclusive value="0"/>
            <xs:maxInclusive value="5"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="favouritenumbers">
        <xs:restriction base="xs:positiveInteger">
            <xs:minInclusive value="1"/>
            <xs:maxInclusive value="10"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="tariffing">
        <xs:restriction base="xs:string">
            <xs:enumeration value="twelve_seconds"/>
            <xs:enumeration value="each_minute"/>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="connectpayment">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="50"/>
            <xs:maxInclusive value="400"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== yaroslava-l/OOP/lab2/Tariff.xml
<?xml version="1.0" encoding="UTF-8"?>
<operator name="MobileCompany"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="Tariff.xsd">
<tariff id="tar1">
    <tariffname>WGold</tariffname>
        <payroll>100</payroll>
        <callprices>
            <insidenetwork>0</insidenetwork>
            <outsidenetwork>15</outsidenetwork>
            <tofixedphones>6</tofixedphones>
        </callprices>
        <smsprice>2</smsprice>
        <parameters>
            <favouritenumbers>10</favouritenumbers>
            <tariffing>twelve_seconds</tariffing>
            <connectpayment>50</connectpayment>
        </parameters>
    </tariff>
<tariff id="tar2">
    <tariffname>Family</tariffname>
    <payroll>250</payroll>
    <callprices>
        <insidenetwork>0</insidenetwork>
        <outsidenetwork>20</outsidenetwork>
        <tofixedphones>6</tofixedphones>
     </callprices>
     <smsprice>2</smsprice>
     <parameters>
        <favouritenumbers>5</favouritenumbers>
        <tariffing>twelve_seconds</tariffing>
        <connectpayment>100</connectpayment>
     </parameters>
</tariff>
<tariff id="tar3">
        <tariffname>your_tr</tariffname>
        <payroll>150</payroll>
        <callprices>
            <insidenetwork>1</insidenetwork>
            <outsidenetwork>5</outsidenetwork>
            <tofixedphones>6</tofixedphones>
        </callprices>
        <smsprice>0</smsprice>
        <parameters>
            <favouritenumbers>2</favouritenumbers>
            <tariffing>each_minute</tariffing>
            <connectpayment>50</connectpayment>
        </parameters>
</tariff>
<tariff id="tar4">
    <tariffname>TTTen</tariffname>
        <payroll>200</payroll>
        <callprices>
        <insidenetwork>10</insidenetwork>
        <outsidenetwork>10</outsidenetwork>
        <tofixedphones>10</tofixedphones>
    </callprices>
    <smsprice>10</smsprice>
    <parameters>
        <favouritenumbers>8</favouritenumbers>
        <tariffing>twelve_seconds</tariffing>
        <connectpayment>40</connectpayment>
    </parameters>
</tariff>
<tariff id="tar5">
    <tariffname>Work</tariffname>
        <payroll>400</payroll>
        <callprices>
        <insidenetwork>0</insidenetwork>
        <outsidenetwork>10</outsidenetwork>
        <tofixedphones>8</tofixedphones>
    </callprices>
    <smsprice>0</smsprice>
    <parameters>
        <favouritenumbers>5</favouritenumbers>
        <tariffing>each_minute</tariffing>
        <connectpayment>100</connectpayment>
    </parameters>
</tariff>
</operator>
